# -*- coding: utf-8 -*-
"""Exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jovvi4WnXyyKfRFZXxgbV0ndyDtt4IXj
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch import Tensor
import torch.optim as optim
from torchmetrics import MeanMetric, AUROC
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from tqdm import tqdm
from models import SimpleLoanModel, LoanModelExtra, LoanModelExtraWithBn, LoanModelExtraWithDropout


if __name__ == "__main__":
  class LoanModel(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(LoanModel, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size * 4)
        self.fc3 = nn.Linear(hidden_size * 4, hidden_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x
  class LoanDataset(Dataset):
    def __init__(self, data: pd.DataFrame, target: pd.Series):
        self.data = data
        self.target = target

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data.iloc[idx]
        target_item = self.target.iloc[idx]
        out = {"num_features": {}, "cat_features": {}}
        for col in item.index:
            if col in cat_features:
                out["cat_features"][col] = torch.tensor(C_MAPS[col][item[col]], dtype=torch.long)
            else:
                out["num_features"][col] = torch.tensor(item[col], dtype=torch.float)
        out["target"] = torch.tensor(target_item, dtype=torch.float)
        return out
  train_data = pd.read_csv('loan_train.csv').drop(columns=["id"])
  test_data = pd.read_csv('loan_test.csv').drop(columns=["id"])

  cat_features = train_data.drop(columns=["loan_status"]).select_dtypes("object").columns
  num_features = train_data.drop(columns=["loan_status"]).select_dtypes("number").columns

  C_MAPS = {
      cat_col:
          {value: encoded_value
              for encoded_value, value in enumerate(train_data[cat_col].unique())}
          for cat_col in cat_features
  }

  scaler = StandardScaler()

  X_scaled = pd.DataFrame(scaler.fit_transform(train_data.drop(columns=["loan_status", *cat_features], axis=1)), columns=num_features)
  Test_scaled = pd.DataFrame(scaler.transform(test_data.drop(columns=["loan_status", *cat_features], axis=1)), columns=num_features)

  X_scaled = pd.concat([X_scaled, train_data[cat_features]], axis=1)
  Test_scaled = pd.concat([Test_scaled, test_data[cat_features]], axis=1)

  x_train, x_val, y_train, y_val = train_test_split(X_scaled, train_data["loan_status"], test_size=0.2, stratify=train_data["loan_status"])

  train_dataset = LoanDataset(x_train, y_train)
  val_dataset = LoanDataset(x_val, y_val)
  test_dataset = LoanDataset(Test_scaled, test_data["loan_status"])


  def train(model: nn.Module, train_dataset: Dataset, eval_dataset: Dataset, config : dict):

      seed = 52
      device = "cuda" if torch.cuda.is_available() else "cpu"
      n_epochs = config["num_epochs"]
      lr = config["lr"]
      weight_decay = config["decay"] if "decay" in config else 0.0
      batch_size = config["batch_size"]

      torch.random.manual_seed(seed)

      model = model.to(device)
      loss_bce = torch.nn.BCEWithLogitsLoss()

      optimizer = torch.optim.SGD(model.parameters(), lr=lr, weight_decay=weight_decay)

      train_dl = DataLoader(train_dataset, batch_size=batch_size, num_workers=4, pin_memory=True)
      eval_dl = DataLoader(eval_dataset, batch_size=batch_size, num_workers=4, pin_memory=True)

      history = {"train_losses": [], "train_auc": [], "val_losses": [], "val_auc": []}
      best_eval_loss = float('inf')

      for i_epoch in tqdm(range(n_epochs)):
          train_loss = MeanMetric().to(device)
          train_rocauc = AUROC(task='binary').to(device)
          for i, batch in enumerate(train_dl):
              num_features, cat_features, target = batch["num_features"], batch["cat_features"], batch["target"].to(device)

              for col in num_features:
                  num_features[col] = num_features[col].to(device)

              for col in cat_features:
                  cat_features[col] = cat_features[col].to(device)

              result = model(num_features=num_features, cat_features=cat_features)


              loss_value = loss_bce(result, target)
              loss_value.backward()
              optimizer.step()
              optimizer.zero_grad()

              train_loss.update(loss_value)
              train_rocauc.update(torch.sigmoid(result), target)

          train_loss = train_loss.compute().item()
          train_rocauc = train_rocauc.compute().item()

          history["train_losses"].append(train_loss)
          history["train_auc"].append(train_rocauc)

          eval_loss = MeanMetric().to(device)
          eval_rocauc = AUROC(task='binary').to(device)


          model.eval()
          with torch.no_grad():
              for i_eval, batch_eval in enumerate(eval_dl):
                  num_features, cat_features, target = batch_eval["num_features"], batch_eval["cat_features"], batch_eval["target"].to(device)

                  for col in num_features:
                      num_features[col] = num_features[col].to(device)

                  for col in cat_features:
                      cat_features[col] = cat_features[col].to(device)

                  result_eval = model(num_features=num_features, cat_features=cat_features)


                  eval_loss_value = loss_bce(result_eval, target)

                  eval_loss.update(eval_loss_value)
                  eval_rocauc.update(torch.sigmoid(result_eval),target)
          model.train()

          eval_loss = eval_loss.compute().item()
          eval_rocauc = eval_rocauc.compute().item()

          history["val_losses"].append(eval_loss)
          history["val_auc"].append(eval_rocauc)

          if eval_loss < best_eval_loss:
              torch.save(model.state_dict(), "model.pt")

      return history


  def test(model: nn.Module, test_dataset: Dataset, config: dict):
      model.eval()

      device = "cuda" if torch.cuda.is_available() else "cpu"

      model = model.to(device)

      test_dl = DataLoader(test_dataset, batch_size=config["batch_size"])

      loss_bce = torch.nn.BCEWithLogitsLoss()
      test_loss = MeanMetric().to(device)
      test_rocauc = AUROC(task='binary').to(device)

      model.eval()
      with torch.no_grad():
          for i_eval, batch in enumerate(test_dl):
              num_features, cat_features, target = batch["num_features"], batch["cat_features"], batch["target"].to(device)

              for col in num_features:
                  num_features[col] = num_features[col].to(device)

              for col in cat_features:
                  cat_features[col] = cat_features[col].to(device)

              result_eval = model(num_features=num_features, cat_features=cat_features)
              loss_value = loss_bce(result_eval, target)

              test_loss.update(loss_value)
              test_rocauc.update(torch.sigmoid(result_eval),target)

      test_loss = test_loss.compute().item()
      test_rocauc = test_rocauc.compute().item()

      return test_loss, test_rocauc


  # Эксперимент 1
  print("Experiment 1")
  config = {
    "num_epochs": 30,
    "lr": 0.01,
    "hidden_size": 32,
    "batch_size": 32
  }
  model_SimpleLoanModel = SimpleLoanModel(config["hidden_size"])

  history = train(
      model=model_SimpleLoanModel,
      train_dataset=train_dataset,
      eval_dataset=val_dataset,
      config=config
  )

  model_SimpleLoanModel.load_state_dict(torch.load("model.pt"))
  metrics1 = test(
      model=model_SimpleLoanModel,
      test_dataset=test_dataset,
      config=config)

  print("Experiment1: metrics ", metrics1)

  # Эксперимент 2
  print("Experiment 2")
  config = {
    "num_epochs": 30,
    "lr": 0.01,
    "hidden_size": 128,
    "batch_size": 64,
    "num_blocks": 3
  }
  model_LoanModelExtra = LoanModelExtra(config["hidden_size"],
                          config["num_blocks"])
  history2 = train(
    model=model_LoanModelExtra,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    config=config
  )

  model_LoanModelExtra.load_state_dict(torch.load("model.pt"))
  metrics2 = test(
    model=model_LoanModelExtra,
    test_dataset=test_dataset,
    config=config)
  print("Experiment2: metrics ", metrics2)

  # Эксперимент 3
  print("Experiment 3")
  config = {
    "num_epochs": 30,
    "lr": 0.01,
    "hidden_size": 128,
    "batch_size": 128,
    "num_blocks": 3
  }
  model_LoanModelExtraWithBn = LoanModelExtraWithBn(config["hidden_size"],
                                  config["num_blocks"])
  history3 = train(
    model=model_LoanModelExtraWithBn,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    config=config
  )

  model_LoanModelExtraWithBn.load_state_dict(torch.load("model.pt"))
  metrics3 = test(
    model=model_LoanModelExtraWithBn,
    test_dataset=test_dataset,
    config=config)
  print("Experiment3: metrics ", metrics3)

  # Эксперимент 4
  print("Experiment 4")
  configs = []
  ps = [0.01, 0.1, 0.2, 0.5, 0.9]
  for p in ps:
      configs.append({
          "num_epochs": 30,
          "lr": 0.01,
          "hidden_size": 128,
          "batch_size": 128,
          "num_blocks": 3,
          "p": p
      })
  model_LoanModelExtraWithDropout = LoanModelExtraWithDropout(config["hidden_size"],
                                    config["num_blocks"],
                                    config["p"])

  history4 = train(
    model=model_LoanModelExtraWithDropout,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    config=config,
  )

  model_LoanModelExtraWithDropout.load_state_dict(torch.load("model.pt"))

  metrics4 = test(
    model=model_LoanModelExtraWithDropout,
    test_dataset=test_dataset,
    config=config)

  print("Experiment4: metrics ", metrics4)


  # Эксперимент 5
  print("Experiment 5")
  configs = []

  lrs = [0.01, 0.05, 0.1]
  decays = [0.1, 0.01, 0.001]

  for lr in lrs:
      for decay in decays:
          configs.append({
              "num_epochs": 50,
              "lr": lr,
              "hidden_size": 128,
              "batch_size": 64,
              "num_blocks": 3,
              "p": 0.1,
              "decay": decay
          })
  model_LoanModelExtraWithDropout = LoanModelExtraWithDropout(config["hidden_size"],
                                    config["num_blocks"],
                                    config["p"])

  history5 = train(
    model=model_LoanModelExtraWithDropout,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    config=config,
  )

  model_LoanModelExtraWithDropout.load_state_dict(torch.load("model.pt"))

  metrics5 = test(
    model=model_LoanModelExtraWithDropout,
    test_dataset=test_dataset,
    config=config)

  print("Experiment5: metrics ", metrics5)

